name: GitHub Actions Demo
on: [push, workflow_dispatch]
permissions:
  id-token: write
  contents: read
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::163705330298:role/test-Role-1KK9U7E79RQ41
          aws-region: us-west-2
      - run: aws sts get-caller-identity --output table
